"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import React, { useState } from "react";
import Navbar from "@/components/Navbar/Navbar";
import styles from "./layout.module.css";
import Searchdock from "@/components/Searchdock/Searchdock";
import { Providers } from "./provdiders";
import TickerTape from "@/components/TickerTape/TickerTape";
import Chart from "@/components/Chart/Chart";
import AboutPara from "@/components/AboutPara/AboutPara";
import Scorecard from "@/components/Scorecard/Scorecard";
import KeyMetrics from "@/components/KeyMetrics/KeyMetrics";
import AboutMetrics from "@/components/AboutMetrics/AboutMetrics";
import ChartX from "@/components/ChartX/ChartX";
import ForecastPrice from "@/components/ForecastPrice/ForecastPrice";
import FinancialsPerformance from "@/components/FinancialsPerformance/FinancialsPerformance";
import FinancialsProfit from "@/components/FinancialsProfit/FinancialsProfit";
import ForecastRecommendation from "@/components/ForecastRecommendation/ForecastRecommendation";

// export const metadata = {
//   title: "Stock Prediction App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [selectedTicker, setSelectedTicker] = useState(null);
  const [isModalBlurred, setIsModalBlurred] = useState(false);

  const handleSearchBarClick = () => {
    setIsModalBlurred(true);
  };

  const handleTickerSelect = (ticker, companyName) => {
    setSelectedTicker(ticker);
  };

  return (
    <html lang="en">
      <head>
        <script
          type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js"
        ></script>
        <script src="https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js"></script>
        <script type="text/javascript" src="index.js"></script>
      </head>

      <body className={styles.main}>
        <Providers>
          <div className={styles.nav}>
            <Navbar />
          </div>

          <div className={styles.rest}>
            <div className={styles.tickerTape}>
              <TickerTape
                items={[
                  "RELIANCE.NS",
                  "TCS.NS",
                  "TATAMOTORS.NS",
                  "INFY.NS",
                  "HDFCBANK.NS",
                  "ICICIBANK.NS",
                  "KOTAKBANK.NS",
                  "HINDUNILVR.NS",
                  "BHARTIARTL.NS",
                  "SBIN.NS",
                  "LT.NS",
                  "AXISBANK.NS",
                  "MARUTI.NS",
                  "ITC.NS",
                  "M&M.NS",
                  "SUNPHARMA.NS",
                ]}
              />
            </div>

            <div className={styles.dock}>
              <Searchdock onTickerSelect={handleTickerSelect} />
            </div>

            <div className={styles.children}>{children}</div>

            <div id="overview" className={styles.chart}>
              <Chart selectedTicker={selectedTicker} />
            </div>

            {/* <div className={styles.scoreCardTitle}>Stock Scorecard</div>
            <div className={styles.scoreCard}>
              <Scorecard />
            </div> */}

            <div className={styles.keyMetricsBG}>
              <div className={styles.keyMetricsBGG}>
                <div className={styles.keyMetricsTitle}>
                  <div className={styles.titleAlign}>Key Metrics</div>
                </div>
                <div className={styles.keyMetrics}>
                  <KeyMetrics selectedTicker={selectedTicker} />
                </div>
              </div>
            </div>

            <div className={styles.aboutTitleBG}>
              <div className={styles.aboutTitleBGG}>
                <div className={styles.aboutTitle}>
                  <div className={styles.titleAlign}>About</div>
                </div>
                <div className={styles.about}>
                  <div className={styles.wrapper}>
                    <div className={styles.aboutContent}>
                      <AboutMetrics selectedTicker={selectedTicker} />
                    </div>
                  </div>
                </div>
                <div className={styles.paraContent}>
                  <AboutPara selectedTicker={selectedTicker} />
                </div>
              </div>
            </div>

            <div id="financials" className={styles.finBG}>
              <div className={styles.finBGG}>
                <div className={styles.keyMetricsTitle}>
                  <div className={styles.titleAlign}>Financials</div>{" "}
                </div>
                <div className={styles.finwrapper}>
                  <div className={styles.finbox}>
                    <FinancialsPerformance selectedTicker={selectedTicker} />
                  </div>
                  <div className={styles.finbox}>
                    <FinancialsProfit selectedTicker={selectedTicker} />
                  </div>
                </div>
              </div>
            </div>

            <div id="forecast" className={styles.forBG}>
              <div className={styles.forBGG}>
                {/* <div className={styles.keyMetricsTitle}> */}
                {/* <div className={styles.titleAlign}>Forecast</div> */}
                <div className={styles.forecast}>
                  <div className={styles.forecastPrice}>
                    <ForecastRecommendation selectedTicker={selectedTicker} />
                    {/* </div> */}
                  </div>
                  <div className={styles.forecastPrice}>
                    <ForecastPrice selectedTicker={selectedTicker} />
                  </div>
                </div>
              </div>
            </div>

            {/* <div className={styles.peerBG}>
              <div className={styles.peerBGG}>
                <div className={styles.keyMetricsTitle}>
                  <div className={styles.titleAlign}>Peers</div>
                  <div className={styles.peerwrapper}><div className={styles.cname}>Company Name</div>
                    <div className={styles.graph}>Graph</div>
                    <div className={styles.info}>Information</div>
                  </div></div>
              </div>
            </div> */}

            {/* <div className={styles.newsBG}>
              <div className={styles.newsBGG}>
                <div className={styles.keyMetricsTitle}>
                  <div className={styles.titleAlign}>News</div>{" "}
                </div>
                <div className={styles.newswrapper}>
                  <div className={styles.newsbox}></div>
                  <div className={styles.newsbox}></div>
                  <div className={styles.newsbox5}></div>
                  <div className={styles.newsbox}></div>
                  <div className={styles.newsbox}></div>
                </div>
              </div>
            </div> */}
          </div>
        </Providers>
      </body>
    </html>
  );
}
